### PR TITLE
bump default version to 2.6.0 release

### PR DESCRIPTION
**Pull request by dereklwood**
default CDAP version bump for 2.6.0 release

### CODE REVIEW

**Comment by duddun** [comment]
:+1:

**Comment by wolf31o2** [comment]
Test failure. I am assuming a bad test, but something could be wrong, here.

**Comment by wolf31o2** [comment]
The test assumes the version is 2.5.2 rather than 2.6.0... we need to reverse the logic in the tests...

**Comment by dereklwood** [comment]
pushed a fix, will see if it fixes.  but do we even need to test now for the old behavior?

**Comment by wolf31o2** [comment]
We should continue to support 2.5 releases, IMO.

**Comment by wolf31o2** [comment]
:+1: LGTM

**Pull request merged**
