### PR TITLE
Set testing log level to error, to remove deprecation spam

### PR DESCRIPTION
**Pull request by wolf31o2**
This sets the log level to error for RSpec runs.

### CODE REVIEW

**Comment by wolf31o2** [comment]
Tests are fixed in #207

**Comment by dereklwood** [comment]
what deprecation messages is it removing?  i don't think i've noticed them before...

**Comment by dereklwood** [comment]
not blocking... 👍 lgtm, but would be nice to know what we are masking

**Comment by wolf31o2** [comment]
This removes most of the warnings, including duplicate resources, but I'm specifically referring to deprecation warnings in dependency cookbooks, like `yum` which just clutter up the build output.

**Pull request merged**
